public class anonCallout {
/*


UserStoryCallOut u = new UserStoryCallOut();
UserStoryCallOut.getUserStory('122790960980');
UserStoryCallOut.updateUserStory('122790960980');

Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setMethod('PUT');
String apiKey = '_84arjdETS9erMHwoAhg2AvToImyjg0mNrXOMCLiaweA';
        //request.setHeader('Content-Type','text/javascript;charset=utf-8');
        request.setHeader('Content-Type', 'text/javascript;charset=UTF-8');
        Blob headerValue = Blob.valueOf('shashikantn@cybage.com' + ':' + 'rally@123');
        String authorizationHeader = 'Basic  ' + EncodingUtil.base64Encode(headerValue);      
        request.setHeader('Authorization', authorizationHeader);
        request.setHeader('ZSESSIONID', apiKey);
    //?zsessionid=_84arjdETS9erMHwoAhg2AvToImyjg0mNrXOMCLiaweA
        request.setEndpoint('https://rally1.rallydev.com/slm/webservice/v2.0/hierarchicalrequirement/122790960980');
        //request.setBody('{"HierarchicalRequirement":{"_ref": "https://rally1.rallydev.com/slm/webservice/v2.0/hierarchicalrequirement/122790960980", "_refObjectUUID": "d67bb0c8-f3d3-4cff-b59f-88db1a796034","ObjectID": 122790960980,"ObjectUUID": "d67bb0c8-f3d3-4cff-b59f-88db1a796034","FormattedID": "US2","Description":"Updated from SF Code."}}');
        request.setBody('{"HierarchicalRequirement":{"Description":"Updated from SF Code."}}');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200){
            System.debug('Successfully updated..');
            system.debug('in if response Status : ' + response.getStatusCode() + ' ' + response.getStatus());
            System.debug('response : '+response.getBody());
        } else {
            system.debug('in else response Status : ' + response.getStatusCode() + ' ' + response.getStatus());
            System.debug('response : '+response.getBody());
        }
        system.debug(response);
        

*/

/*


setup/systemOverview.apexp

ApiUsage__c
ApiAllocation__c
DataStorageUsage__c


setup/org/orgstorageusage

FileStorageLimit__c
FileStorageUsed__c
FileStoragePercentUsed__c


UnmanagedCustomObjects__c
UnmanagedCustomApps__c
UnmanagedCustomTabs__c

InstalledPackages   : Got using SOQL 

    HRMPackageVersion__c
    Challenge : Metadata API    -   readMetadata
    


TotalLicensedSalesforceUsers__c
TotalLicensedSalesforcePlatformUsers__c
TotalActiveSalesforceUsers__c
TotalActiveSalesforcePlatformUsers__c

*/


}