public class personal {
/*
  Project Description: The objective was to synch L3 cases between Salesforce Case Management and Rally Defect Management. The synchronization includes the following elements

-	Sales force Case details

-	Salesforce Comments for a given case as it progress

-	Salesforce Attachments for a given case as it progress


During the synchronization, the solution updates the fields and also notifies about the changes to the recipients. All the stakeholders were given get a real-time view in Rally and Salesforce on tickets (Cases).

Rally Support Manager “AppExchange” Component from Rally Dev was used for the implementation. Rally provided the basic connector and also there was provision to extend them to achieve the custom functionality seamlessly. User experience is enhanced with the Salesforce having the greater control to push or pull the relevant data.


Roles and Responsibilities in the project:

-	Perform requirement analysis and system design

-	Used the managed package “Rally Support Manager” for configuration and establishing relation between Salesforce and Rally

-	Worked on synchronization from Salesforce to Rally and Rally to Salesforce

-	Worked to provide provision for synchronizing each at element level.

-	Used Web service call out using JavaScript

-	Peer code reviews

-	Unit Testing and Deploymen
  
    
    
*/    
}