public class PERSONAL_INFO {

}
/*

HDFC FUND DETAILS
SHASHI_NIKAM87
My Pet name : MOTI
firstfund@123


HDFC Mutual Fund
shashi_nikam
trysip@123
Pet Name : Moti 




IRCTC 
s_nikam05
Goatrip123

s_nikam05
Trains@123
0797

NPS:
PRAN No : 	110028057995
Password : 	newpass@123

PF NO 	:	MH/33604/0004844
UAN NO	:	100381699404
PRAN NO	:	110028057995



cibil site 
Password : Mycibil@123

MEDICLAIM WEBSITE 
shashi.nikam87@gmail.com	
Newpass@123

ZERODHA :
1. power on left eye : zero
2. name of movie hall near to residence : inorbit
3. company where u start career : tricom
4. mobile brand : asus
5. shampoo brand : panteen



MONEYCONTROL.COM
	shashi_nikam87
	trymarketing@123


CHOICE BROKING

5 Questions : 

	1. Who was/is your best friend in school?  - Tushar
	2. Which web-site you created your first e-mail account? (e.g. Rediff, Sify, Office, etc) - yahoo
	3. Previous company where you worked? ( e.g. TCS, Infosys, etc) - Tricom
	4. What is your favourite colour? - Blue
	5. Colour of your first car? (e.g. Red, White etc) - Silver


*/